language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-presentation' ]; then cd .. && eval "mv $currentfolder generator-presentation" && cd generator-presentation; fi
  - npm install -g gulp
