language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-impressive' ]; then cd .. && eval "mv $currentfolder generator-impressive" && cd generator-impressive; fi
  - npm install -g gulp
